name: Github Actions
on: [push, pull_request]
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        nim-version: ['1.2.2', '1.2.x', '1.4.x', '1.6.x', '2.0.x', 'stable']
        include:
          - nim-version: '1.4.x'
            gc_orc: true
          - nim-version: '1.6.x'
            gc_orc: true
          - nim-version: 'stable'
            do_js: true

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4
    - uses: jiro4989/setup-nim-action@v2
      with:
        nim-version: ${{ matrix.nim-version }}
        repo-token: ${{ secrets.GITHUB_TOKEN }}
    - run: nimble test -y
    - run: nimble test -d:release -y
    - run: nimble test --gc:orc -d:release -y
      if: ${{ matrix.gc_orc }}
    - run: nim js -r tests/test.nim
      if: ${{ matrix.do_js }}
